Feat : Add Images and Inputs
OmKakatkar/Ani-Design pull request #9
Opened 2022-02-07 18:26 UTC by OmKakatkar

- Added circular images
- Added responsive images which scale as per container
- Added 5 different sizes for images.
- Class `circular` can also be used with all the different sizes.
- Added styles for text (includes text-area) input along with error and success validation.
- Added custom checkbox and radio button.
- Live Preview Available in the comments by Netlify bot.

2022-02-07 18:43 UTC, anandsr21harshit approved these changes

2022-02-07 19:31 UTC, thegeorgenikhil requested changes

2022-02-07 19:31 UTC, thegeorgenikhil commented on css/components/image.css
> +}
use rems instead of px

2022-02-08 02:52 UTC, OmKakatkar commented on css/components/image.css
> +}
Yes, working on it.

2022-02-08 07:12 UTC, merged